from fastapi import FastAPI
from fastapi.responses import HTMLResponse

from backend.app.health import router as health_router
from backend.app.leads.routes import router as leads_router

LOCAL_DOCS_HTML = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SalesOps Workflow Automation Hub API Docs</title>
    <style>
      :root {
        color-scheme: light;
        font-family: Arial, Helvetica, sans-serif;
        background: #f6f7f9;
        color: #172033;
      }

      body {
        margin: 0;
        min-height: 100vh;
      }

      main {
        max-width: 880px;
        margin: 0 auto;
        padding: 48px 24px;
      }

      h1 {
        margin: 0 0 12px;
        font-size: 2rem;
        line-height: 1.2;
      }

      p {
        max-width: 720px;
        color: #39465e;
        line-height: 1.65;
      }

      a {
        color: #0f5ea8;
        font-weight: 700;
      }

      .panel {
        margin-top: 28px;
        border: 1px solid #d8dee9;
        border-radius: 8px;
        background: #ffffff;
        padding: 24px;
      }

      code {
        border-radius: 4px;
        background: #eef2f7;
        padding: 2px 6px;
      }
    </style>
  </head>
  <body>
    <main>
      <h1>SalesOps Workflow Automation Hub API Docs</h1>
      <p>
        This local documentation page intentionally avoids remote runtime
        assets. Use the OpenAPI JSON document for endpoint details, schemas,
        and local demo integration evidence.
      </p>
      <section class="panel" aria-labelledby="openapi-heading">
        <h2 id="openapi-heading">OpenAPI contract</h2>
        <p>
          Open the local API schema at <a href="/openapi.json">/openapi.json</a>.
          The schema is generated by the FastAPI application and remains
          available for local inspection and tooling.
        </p>
        <p>
          Local reviewer routes include <code>/health</code>,
          <code>/leads/intake</code>, and <code>/leads/runs</code>.
        </p>
      </section>
    </main>
  </body>
</html>
"""


def local_docs() -> HTMLResponse:
    return HTMLResponse(content=LOCAL_DOCS_HTML)


def create_app() -> FastAPI:
    application = FastAPI(
        title="SalesOps Workflow Automation Hub API",
        version="0.1.0",
        summary="Local-first backend foundation with mocked integrations by default.",
        docs_url=None,
        redoc_url=None,
    )
    application.add_api_route(
        "/docs",
        local_docs,
        methods=["GET"],
        include_in_schema=False,
    )
    application.include_router(health_router)
    application.include_router(leads_router)
    return application


app = create_app()
